name: tests

on:
  push:
    branches: [main]
    tags: v*
  pull_request:

jobs:
  run_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: extractions/setup-just@v1

    - name: Install poetry
      run: |
        python -m pip install poetry

    - name: Prepare project for development
      run: |
        just setup

    - name: Run tests
      run: |
        # tests run git commands to creat git commaits, and they need a
        # proper identity for that
        git config --global user.email "test@tbump-tests.com"
        git config --global user.name "Tasty Test"
        just test
